# Generated by Django 2.0.13 on 2019-07-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='image',
        ),
    ]
