# Generated by Django 2.0.13 on 2019-07-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20190725_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
